// src/@types/global.d.ts

interface RazorpayPayment {
    razorpay_order_id: string;
    razorpay_payment_id: string;
    razorpay_signature: string;
}

interface RazorpayOptions {
    key: string; // The key ID provided by Razorpay
    amount: number; // Amount in paise
    currency: string; // Currency code
    name: string; // Name of the business
    description?: string; // Description of the payment
    order_id: string; // Order ID generated by Razorpay
    handler: (response: RazorpayPayment) => void; // Handler for payment success
    prefill?: {
        name?: string;
        email?: string;
        contact?: string;
    };
    theme?: {
        color?: string;
    };
}

interface Razorpay {
    open: () => void; // Method to open the payment modal
    close: () => void; // Method to close the payment modal
    on: (event: string, callback: () => void) => void; // Event listener
}

declare global {
    interface Window {
        Razorpay: new (options: RazorpayOptions) => Razorpay; // Constructor for Razorpay
    }
}

// This line is necessary to make the file a module
export {};